### ISSUE TITLE
Expo 51 support

### ISSUE THREAD

**Issue by coyksdev** [msasinowski/react-native-expo-braintree#16]
When trying to prebuild in Expo 51, it gives an error below

<img width="1047" alt="Screenshot 2024-07-14 at 12 03 28 PM" src="https://github.com/user-attachments/assets/f4b7eb48-18c0-4528-a970-6cb686395343">

**Comment by msasinowski** [comment]
hey @coyksdev as you can find that in the docs, the minimum deployment target is 14.0 

<img width="883" alt="image" src="https://github.com/user-attachments/assets/2fa90515-4080-4087-97cd-76c5a342ba01">

You can achieve that by e.g.

`plugins: [
    // ...other plugins
    [
      "expo-build-properties",
      {
        ios: {
          deploymentTarget: "14.0",
        },
      },
    ],
  ],`

**Comment by coyksdev** [comment]
Thanks @msasinowski !
