### ISSUE TITLE
Documentation guide on how to contribute

### ISSUE THREAD

**Issue by coyksdev** [msasinowski/react-native-expo-braintree#17]
Can you create a guide on how we can contribute?

**Comment by msasinowski** [comment]
hey, @coyksdev  there is an existing https://github.com/msasinowski/react-native-expo-braintree/blob/main/CONTRIBUTING.md CONTRIBUTING.md file in the repo, also this whole package is based on  https://callstack.github.io/react-native-builder-bob/create , I think that's enough information to at least start, but I am open to any feedback or any additional things that I can add to support it, Can you elaborate on that a little bit more?

**Comment by coyksdev** [comment]
> hey, @coyksdev there is an existing https://github.com/msasinowski/react-native-expo-braintree/blob/main/CONTRIBUTING.md CONTRIBUTING.md file in the repo, also this whole package is based on https://callstack.github.io/react-native-builder-bob/create , I think that's enough information to at least start, but I am open to any feedback or any additional things that I can add to support it, Can you elaborate on that a little bit more?

Oops. I didn't see that. thanks! I would like to know how to test it locally, for example I added a method in android/ios and would like to test it if it is working.

**Comment by msasinowski** [comment]
I think, for the end testing you will need to do also the Backend part of the integration, this package is only responsible for creating a payment nonce which later you can use on the backend side to call and charge the account.

Please check these links from Braintree Pages
https://developer.paypal.com/braintree/docs/guides/payment-method-types-overview
https://developer.paypal.com/braintree/docs/start/overview

**Comment by msasinowski** [comment]
I am not so sure about the GPay, but if the client integration generates the nonce from GPay then everything is in place and ready at least on the client side, I assume you follow these ones 

https://developer.paypal.com/braintree/docs/guides/google-pay/overview
https://developer.paypal.com/braintree/docs/guides/google-pay/client-side/android/v4

It looks very similar to what I had done for already covered flow's
