### ISSUE TITLE
ExpoBraintreeModuleHandlers type mismatch

### ISSUE THREAD

**Issue by KruyChandara** [msasinowski/react-native-expo-braintree#27]
Hello! I got a build error when trying to run Android `ExpoBraintreeModuleHandlers.kt:36:21 Type mismatch: inferred type is String? but String is expected`

![Screenshot 2024-11-27 at 2 00 32 in the afternoon](https://github.com/user-attachments/assets/4de6c874-cb6d-4037-96d9-459b8706e6c3)

Environment: 
- expo52
- openjdk 23.0.1
- expo-braintree both 2.4.0 and 3.0.1

Is this a bug or it's because something wrong with my environment?

**Comment by msasinowski** [comment]
hey, I think that's cuz the combination of expo52 + openjdk 23.0.1, It is an easy fix on the package side, but do you have any other build issue using that combination @KruyChandara in any other file or this is the only place ?

**Comment by msasinowski** [comment]
perfect I will make that change and release 2.4.1 and 3.0.2 today and maybe mark this package as compliant with Expo 52 :)
