### ISSUE TITLE
Unresolve reference: createError

### ISSUE THREAD

**Issue by KruyChandara** [msasinowski/react-native-expo-braintree#31]
Hello! Thank you for fixing https://github.com/msasinowski/react-native-expo-braintree/issues/27 very quickly.
I have tried expo-braintree `3.0.3` and seems like I got a different error this time at the same place in ExpoBraintreeModuleHandlers.

![Screenshot 2024-11-28 at 8 08 41 in the evening](https://github.com/user-attachments/assets/25719e82-c40e-439c-865c-8b316437f3ab)

Environment:

- expo52
- openjdk 23.0.1
- expo-braintree both 3.0.3

**Comment by msasinowski** [comment]
> It seems like `createError` dose not exist in `PaypalDataConverter`

ohh correct, DataConverter is only in 2.x branch I will fix that today

**Comment by msasinowski** [comment]
Fixed in 3.0.4
